# Generated by Django 5.2.9 on 2026-01-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academichistory',
            options={'managed': False, 'verbose_name_plural': 'Academic Histories'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studentlevel',
            options={'managed': False},
        ),
    ]
