# Generated by Django 5.2.9 on 2026-01-02 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0006_alter_staffprofile_unique_together_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('office_address', models.TextField(blank=True)),
                ('income_level', models.CharField(blank=True, max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_record', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('can_pickup', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='families.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'parent')},
            },
        ),
    ]
