# Generated by Django 5.2.9 on 2026-01-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='studentparentrelation',
            options={'managed': False},
        ),
    ]
