# Generated by Django 5.2.9 on 2025-12-29 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='institution/banners/')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to='organizations.organization')),
            ],
        ),
    ]
