# Generated by Django 5.2.9 on 2026-01-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('profiles', '0002_institutionprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='organization',
            field=models.OneToOneField(help_text='Linked Organization', on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to='organizations.organization'),
        ),
    ]
