# Generated by Django 5.2.9 on 2026-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_institutionprofile_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_id',
            field=models.CharField(max_length=50),
        ),
    ]
