# Generated by Django 5.2.9 on 2026-01-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_institutionprofile_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionprofile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False, 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
