# Generated by Django 5.2.9 on 2026-01-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_institutionprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionprofile',
            options={'verbose_name': 'Institution Profile', 'verbose_name_plural': 'Institution Profiles'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
