# Generated by Django 5.2.9 on 2026-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_institutionprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
